# Generated by Django 2.1.7 on 2019-03-15 22:18

from django.db import migrations, models
import django.db.models.deletion
import rakhimovse.datradebot.models


class Migration(migrations.Migration):

    dependencies = [
        ('datradebot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.CharField(default=rakhimovse.datradebot.models.get_promo, max_length=8, primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('day7', '7 days'), ('month1', '1 month'), ('month3', '3 months'), ('month6', '6 months'), ('month12', '12 months')], default='day7', max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rakhimovse.datradebot.User')),
            ],
        ),
    ]
