# Generated by Django 2.1.7 on 2019-03-16 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datradebot', '0002_promo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promo',
            name='user',
        ),
        migrations.AddField(
            model_name='promo',
            name='subscription',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='rakhimovse.datradebot.Subscription'),
        ),
    ]
