# Generated by Django 2.1.7 on 2019-03-16 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datradebot', '0003_auto_20190316_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='valid_until',
            new_name='active_until',
        ),
        migrations.AddField(
            model_name='promo',
            name='active_until',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)),
        ),
    ]
